name: Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy Backend to Render
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}"

      - name: Deploy Frontend to Render
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}"