version: '3.8'

services:
  fantasy-backend:
    image: ${DOCKER_USER:-asafshai}/fantasy-backend:${IMAGE_TAG:-latest}
    container_name: fantasy-backend-prod
    ports:
      - "8000:8000"
    
    environment:
      ESPN_STANDINGS_URL: ${ESPN_STANDINGS_URL}
      ESPN_PLAYERS_URL: ${ESPN_PLAYERS_URL}
      ENVIRONMENT: production
      PORT: 8000
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:5173}
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s